pygments: true
relative_permalinks: false
permalink: /:categories/:title/
repository: https://github.com/pathawks/jekyll-meta

exclude:
  - cname
  - README.md
  - LICENSE

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
